options:
  image-registry:
    type: string
    default: k8s.gcr.io
    description: |
      Source registry of metrics server images.

      By setting to a value, each image listed in the releases manifest
      has its image-registry replaced.

      If unset, the manifests will use the image registry from the kube-control relation

      example)
        juju config gcp-k8s-storage image-registry=''

        juju config kubernetes-metrics-server --reset image-registry

  storage-release:
    type: string
    description: |
      Specify the version of storage-provider as defined by the `release`
      tags of https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver

      example)
        juju config gcp-k8s-storage storage-release='v1.7.3'
      
      A list of supported versions is available through the action:
        juju run-action gcp-k8s-storage/0 list-releases --wait
      
      To reset by to the latest supported by the charm use:
        juju config gcp-k8s-storage --reset storage-release
      
      The current release deployed is available by viewing
        juju status gcp-k8s-storage